[package]
name = "netns-rs"
version = "0.1.0"
authors = ["Carlos Valiente <carlos@pepelabs.net>"]
edition = "2018"

[dependencies]
clap = {version = "2.33.1", default-features = false}
netlink-packet-route = "0.2.1"
netlink-sys = "0.2.0"
tokio = "0.2.20"
